// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations need a direct (non-pooled) connection - a pooled connection
    // (e.g. Neon/PgBouncer) can't hold the session-level advisory lock
    // `migrate deploy` uses, and times out with error P1002. The app itself
    // still connects via DATABASE_URL (see src/lib/prisma.ts), so it's free
    // to stay on the pooled URL for better serverless concurrency.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
